language: python
python:
  - "3.6"

os:
  - linux

install:
  - pip3 install pipenv
  - pipenv install

script:
  - pipenv run mypy src/*
  - pipenv run pylint src/*
  - pipenv run pytest -vv -s -x

notifications:
    email: false

