language: python
python:
  - "3.6.2"

os:
  - linux

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip3 install pipenv
  - pipenv run python setup.py install
  - pipenv install --dev

script:
  - pipenv run mypy github_stargazers/*
  - pipenv run pylint github_stargazers/*
  - pipenv run pytest -vv

notifications:
    email: false

